#!/usr/bin/env ruby -w
require 'date'
require 'fileutils'

# OMG PLZ SEND PULL REQUESTS WITH MORE AWESOME MSGS
messages = [
  "My kid's appointment at the pediatrician can wait, I need to get this commit in.",
  "Sorry honey, I need to keep my streak going - we'll have sex tomorrow!",
  "This commit brought to you by my privilege.",
  "My employer lets me use work time to contribute to open source."
]

rr = %w{ Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you\n }

gh_founding = DateTime.new(2008,7,21)

# yay sloppy!
raise 'plz run from master, kthx' unless `git rev-parse --abbrev-ref HEAD`.strip == 'master'

`git branch -D i-am-my-commits` if system 'git show-ref --verify -q refs/heads/i-am-my-commits'
`git branch -q i-am-my-commits; git checkout i-am-my-commits`

i = 0
gh_founding.to_date.step(Date.today) do |day|
  File.open('self_worth', 'a') { |f| f.write(rr[i % 34]) }
  File.open('msg', 'w') { |f| f.write(messages.sample) }
  system({'GIT_COMMITTER_DATE' => day.rfc2822, 'GIT_AUTHOR_DATE' => day.rfc2822}, "git commit -q -F msg -- self_worth")
  i += 1
end

FileUtils.rm 'msg'

puts 'Now show the world you are worth the physical space your body occupies - PUSH TO GITHUB! (`git push origin i-am-my-commits`)'
